definitions:
  health_handler.HealthResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: communication serviceのWebAPI
  title: communication service web api
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      description: ヘルスチェック
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health_handler.HealthResponse'
      summary: ヘルスチェック
      tags:
      - health
swagger: "2.0"
